/*
CCDM RS Table mapping
Notes: Standard mapping to CCDM RS table
*/

WITH included_subjects AS (
                SELECT DISTINCT studyid, siteid, usubjid FROM subject),
    rs_data AS (
        SELECT  null::text AS comprehendid,
                null::text AS studyid,
                null::text AS siteid,
                null::text AS usubjid,
                null::numeric AS rsseq,
                null::text AS rsgrpid,
                null::text AS rsrefid,
                null::text AS rsspid,
                null::text AS rslnkid,
                null::text AS rslnkgrp,
                null::text AS rstestcd,
                null::text AS rstest,
                null::text AS rscat,
                null::text AS rsscat,
                null::text AS rsorres,
                null::text AS rsorresu,
                null::text AS rsstresc,
                null::numeric AS rsstresn,
                null::text AS rsstresu,
                null::text AS rsstat,
                null::text AS rsreasnd,
                null::text AS rsnam,
                null::text AS rslobxfl,
                null::text AS rsblfl,
                null::text AS rsdrvfl,
                null::text AS rseval,
                null::text AS rsevalid,
                null::text AS rsacptfl,
                null::numeric AS visitnum,
                null::text AS visit,
                null::numeric AS visitdy,
                null::numeric AS taetord,
                null::text AS epoch,
                null::text AS rsdtc,
                null::numeric AS rsdy,
                null::text AS rstpt,
                null::numeric AS rstptnum,
                null::text AS rseltm,
                null::text AS rstptref,
                null::text AS rsrftdtc,
                null::text AS rsevlint,
                null::text AS rsevintx,
                null::text AS rsstrtpt,
                null::text AS rssttpt,
                null::text AS rsenrtpt,
                null::text AS rsentpt
                )

SELECT
    /*KEY (rs.studyid || '~' || rs.siteid || '~' || rs.usubjid)::text AS comprehendid, KEY*/  
    rs.studyid::text AS studyid,
    rs.siteid::text AS siteid,
    rs.usubjid::text AS usubjid,
    rs.rsseq::numeric AS rsseq,
    rs.rsgrpid::text AS rsgrpid,
    rs.rsrefid::text AS rsrefid,
    rs.rsspid::text AS rsspid,
    rs.rslnkid::text AS rslnkid,
    rs.rslnkgrp::text AS rslnkgrp,
    rs.rstestcd::text AS rstestcd,
    rs.rstest::text AS rstest,
    rs.rscat::text AS rscat,
    rs.rsscat::text AS rsscat,
    rs.rsorres::text AS rsorres,
    rs.rsorresu::text AS rsorresu,
    rs.rsstresc::text AS rsstresc,
    rs.rsstresn::numeric AS rsstresn,
    rs.rsstresu::text AS rsstresu,
    rs.rsstat::text AS rsstat,
    rs.rsreasnd::text AS rsreasnd,
    rs.rsnam::text AS rsnam,
    rs.rslobxfl::text AS rslobxfl,
    rs.rsblfl::text AS rsblfl,
    rs.rsdrvfl::text AS rsdrvfl,
    rs.rseval::text AS rseval,
    rs.rsevalid::text AS rsevalid,
    rs.rsacptfl::text AS rsacptfl,
    rs.visitnum::numeric AS visitnum,
    rs.visit::text AS visit,
    rs.visitdy::numeric AS visitdy,
    rs.taetord::numeric AS taetord,
    rs.epoch::text AS epoch,
    rs.rsdtc::text AS rsdtc,
    rs.rsdy::numeric AS rsdy,
    rs.rstpt::text AS rstpt,
    rs.rstptnum::numeric AS rstptnum,
    rs.rseltm::text AS rseltm,
    rs.rstptref::text AS rstptref,
    rs.rsrftdtc::text AS rsrftdtc,
    rs.rsevlint::text AS rsevlint,
    rs.rsevintx::text AS rsevintx,
    rs.rsstrtpt::text AS rsstrtpt,
    rs.rssttpt::text AS rssttpt,
    rs.rsenrtpt::text AS rsenrtpt,
    rs.rsentpt::text AS rsentpt
    /*KEY , (rs.studyid || '~' || rs.siteid || '~' || rs.usubjid || '~' || rs.rstestcd || '~' || rs.rseval || '~' || rs.rsevalid || '~' || rs.visitnum || '~' || rs.rstptnum || '~' || rs.rstptref )::text  AS objectuniquekey KEY*/
    /*KEY , now()::timestamp with time zone AS comprehend_update_time KEY*/
FROM rs_data rs JOIN included_subjects s ON (rs.studyid = s.studyid AND rs.siteid = s.siteid AND rs.usubjid = s.usubjid)
WHERE 1=2;
